"""fix samlprovider column name

Revision ID: 1a4e1fa2c264
Revises: 578c2cd5d9a0
Create Date: 2026-05-18 03:25:56.683629

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a4e1fa2c264'
down_revision = '578c2cd5d9a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saml_providers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('idp_sso_url', sa.String(length=512), nullable=False))
        batch_op.drop_column('idp_ssol_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saml_providers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('idp_ssol_url', sa.VARCHAR(length=512), nullable=False))
        batch_op.drop_column('idp_sso_url')

    # ### end Alembic commands ###
