"""fix model

Revision ID: 494e09683d86
Revises: 1a4e1fa2c264
Create Date: 2026-05-18 03:55:42.505221

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '494e09683d86'
down_revision = '1a4e1fa2c264'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saml_providers', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=26),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saml_providers', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.String(length=26),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
