"""add saml sp signing keys

Revision ID: 578c2cd5d9a0
Revises: 93cfadf765c6
Create Date: 2026-05-17 22:19:13.201376

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '578c2cd5d9a0'
down_revision = '93cfadf765c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
