"""fix model

Revision ID: 580f467d7149
Revises: 98e55b4e677c
Create Date: 2026-05-16 05:01:36.766544

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '580f467d7149'
down_revision = '98e55b4e677c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('org_domains', schema=None) as batch_op:
        batch_op.alter_column('verification_token',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('org_domains', schema=None) as batch_op:
        batch_op.alter_column('verification_token',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)

    # ### end Alembic commands ###
