"""add saml_providers

Revision ID: 7f500e7c6b24
Revises: 580f467d7149
Create Date: 2026-05-17 01:14:52.991834

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f500e7c6b24'
down_revision = '580f467d7149'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saml_providers',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('organization_id', sa.String(length=255), nullable=False),
    sa.Column('idp_entity_id', sa.String(length=512), nullable=False),
    sa.Column('idp_ssol_url', sa.String(length=512), nullable=False),
    sa.Column('idp_x509_cert', sa.Text(), nullable=False),
    sa.Column('name_id_format', sa.String(length=255), nullable=False),
    sa.Column('email_attribute', sa.String(length=255), nullable=True),
    sa.Column('name_attribute', sa.String(length=255), nullable=True),
    sa.Column('enforce_sso', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_saml_providers_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_saml_providers'))
    )
    with op.batch_alter_table('saml_providers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_saml_providers_organization_id'), ['organization_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saml_providers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_saml_providers_organization_id'))

    op.drop_table('saml_providers')
    # ### end Alembic commands ###
