"""add saml signing key

Revision ID: 93cfadf765c6
Revises: 7f500e7c6b24
Create Date: 2026-05-17 01:18:00.811936

"""
from alembic import op
import sqlalchemy as sa
from relay.security.encryption import EncryptedString

# revision identifiers, used by Alembic.
revision = '93cfadf765c6'
down_revision = '7f500e7c6b24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saml_providers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sp_private_key', EncryptedString(length=4096), nullable=True))
        batch_op.add_column(sa.Column('sp_certificate', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saml_providers', schema=None) as batch_op:
        batch_op.drop_column('sp_certificate')
        batch_op.drop_column('sp_private_key')

    # ### end Alembic commands ###
