"""add organization and sso models

Revision ID: 98e55b4e677c
Revises: 
Create Date: 2026-05-16 04:09:00.451858

"""
from alembic import op
import sqlalchemy as sa
from relay.security.encryption import EncryptedString

# revision identifiers, used by Alembic.
revision = '98e55b4e677c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organizations'))
    )
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_organizations_slug'), ['slug'], unique=True)

    op.create_table('oidc_providers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.String(length=255), nullable=False),
    sa.Column('issuer', sa.String(length=512), nullable=False),
    sa.Column('client_id', sa.String(length=255), nullable=False),
    sa.Column('client_secret', EncryptedString(length=1024), nullable=False),
    sa.Column('enforce_sso', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_oidc_providers_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_oidc_providers'))
    )
    with op.batch_alter_table('oidc_providers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_oidc_providers_organization_id'), ['organization_id'], unique=True)

    op.create_table('org_domains',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.String(length=255), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('verification_token', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_org_domains_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_org_domains'))
    )
    with op.batch_alter_table('org_domains', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_org_domains_domain'), ['domain'], unique=True)
        batch_op.create_index(batch_op.f('ix_org_domains_organization_id'), ['organization_id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('organization_id', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_users_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('organization_id', 'email', name='uq_user_org_email')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_external_id'), ['external_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_organization_id'), ['organization_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_organization_id'))
        batch_op.drop_index(batch_op.f('ix_users_external_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('org_domains', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_org_domains_organization_id'))
        batch_op.drop_index(batch_op.f('ix_org_domains_domain'))

    op.drop_table('org_domains')
    with op.batch_alter_table('oidc_providers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_oidc_providers_organization_id'))

    op.drop_table('oidc_providers')
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organizations_slug'))

    op.drop_table('organizations')
    # ### end Alembic commands ###
